services:
  bot:
    depends_on:
      - db
    build: .
    environment:
      APIKEY: AIzaSyBnx53Fd2Ss6m-AmHpzWAA6qXtofU6VTgI
      CALLBACK_ORIGIN: develop2-server.kazugmx.site
      JWT_SECRET: 2c76bb510487da449778517eb93750d8de9df1d91f00efd46afebf14b1a4f62f
      SERVER_PORT: 38080
      URI_MASTER: d605cc94fbdc6b9d09c061315d4d92bf
    ports:
      - 38080:38080
    volumes:
      - ./compose-test/data:/app/data
      - ./compose-test/logs:/app/logs
  db:
    image: postgres:18-alpine
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: botuser_alpha
      POSTGRES_PASSWORD: testpassword_alpha
      POSTGRES_DB: botdb_alpha
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./compose-test/db:/var/lib/postgresql/data:rw