ktor:
  application:
    modules:
      - net.kazugmx.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://${CALLBACK_ORIGIN:invalidOrigin}"
  audience: "jwt-audience"
  realm: "narubox-bot"
  issuer: "narubox-auth"
  secret: "${JWT_SECRET:invalidSecret}"
db:
  url: "jdbc:sqlite:data/bot_data.db"
youtube:
  apikey: "${APIKEY:invalidKey}"
  callbackOrigin: "${CALLBACK_ORIGIN:invalidOrigin}"