ktor:
  application:
    modules:
      - net.kazugmx.ApplicationKt.module
  deployment:
    port: $SERVER_PORT:8080
jwt:
  domain: "https://${CALLBACK_ORIGIN:invalidOrigin}"
  audience: "jwt-audience"
  realm: "narubox-bot"
  issuer: "narubox-auth"
  secret: "${JWT_SECRET:invalidSecret}"
db:
  url: ${JDBC_URL:jdbc:sqlite:data/bot_data.db}
youtube:
  apikey: "${APIKEY:invalidKey}"
  callbackOrigin: "${CALLBACK_ORIGIN:invalidOrigin}"
  uri_master: "${URI_MASTER:invalidURIMaster}"